# Generated by Django 5.0.3 on 2024-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("patronymic", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("age", models.IntegerField(null=True)),
                ("nationality", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
